[build]
command = "rm -rf __obsidian __site && mkdir __obsidian && mv * __obsidian || true && git clone https://github.com/ppeetteerrs/obsidian-zola.git __site && __site/run.sh"
publish = "public"

[build.environment]
LANDING_BUTTON = "Explorer👆"
LANDING_DESCRIPTION = "Ce site est un guide pour les contrôleurs aériens virtuels principalement basé sur le réseau IVAO."
LANDING_PAGE = "home"
LANDING_TITLE = "Get ready for take off 🛫"
PYTHON_VERSION = "3.8"
REPO_URL = "https://github.com/iverly/atc-aviation-obsidian"
SITE_TITLE = "ATC Aviation Guide 🛫"
SITE_TITLE_TAB = ""
SITE_URL = "https://atc.aviation.guide.iverly.net"
TIMEZONE = "Europe/Paris"
ZOLA_VERSION = "0.15.2"
SORT_BY = "title"
GANALYTICS = ""
SLUGIFY = "y"
HOME_GRAPH = ""
PAGE_GRAPH = ""
SIDEBAR_COLLAPSED = ""
FOOTER = ""
ROOT_SECTION_NAME = "main"
GRAPH_OPTIONS = """
        {
        	nodes: {
        		shape: "dot",
        		color: isDark() ? "#8c8e91" : "#dee2e6",
        		font: {
        			face: "Inter",
        			color: isDark() ? "#c9cdd1" : "#616469",
        			strokeColor: isDark() ? "#c9cdd1" : "#616469",
        		},
        		scaling: {
        			label: {
        				enabled: true,
        			},
        		},
        	},
        	edges: {
        		color: { inherit: "both" },
        		width: 0.8,
        		smooth: {
        			type: "continuous",
        		},
        		hoverWidth: 4,
        	},
        	interaction: {
        		hover: true,
        	},
        	height: "100%",
        	width: "100%",
        	physics: {
        		solver: "repulsion",
        	},
        }
        """
